baseurl = "https://berliner-sammelapp.de"               
title = "Berliner Sammelapp"
author = "Simon"
enableRobotsTXT = true
defaultContentLanguage = "de"
language = "de"
paginate = 7
theme = "LoveIt"
images = ["/logo.png"]

[languages]
  [languages.de]
    languageCode = "de"
    languageName = "Deutsch"
    weight = 1
  [languages.en]
    languageCode = "en"
    languageName = "Englisch"
    weight = 2

[params]
  version = "0.2.X"
  defaultTheme = "auto"

  # Home page config
  [params.home]
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      avatarURL = "/images/1024.png"
      title = "Berliner Sammelapp"
      subtitle = ""
      typeit = false
      social = true
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
    [params.social]
      enable = true
      [params.social.appstore]
        URL = "https://apps.apple.com/us/app/berliner-sammel-app/id1619980654"
      [params.social.playstore]
        URL = "https://play.google.com/store/apps/details?id=berlin.sammelapp"
  [params.footer]
    enable = false
    # Header config
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      logo = ""
      name = "Berliner Sammelapp"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1